import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StarCanvas from "./components/Starbg";
import Nav from "./components/Nav";
import { UIProviders } from "./providers/NextUIProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen w-full overflow-y-auto min-w-[360px] overflow-x-hidden">
        <StarCanvas />
        <UIProviders>{children}</UIProviders>
      </body>
    </html>
  );
}
